name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        PY_VERSION: ${{ matrix.python-version }}
      run: |
        PY_VERSION=$PY_VERSION docker-compose run --rm test
